# logging level
logging:
  level:
    root: info
    sql: error

spring:
  mvc:
    # HiddenMethodFilter
    hiddenmethod:
      filter:
        enabled: true
  # database settings
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # session
  server:
    servlet:
      session:
        timeout: 10m